"""Generate an idempotent Postgres import SQL file from ``data/kols.json``.

Output matches the structure of the original ``kol_full_import_clean_1.sql``
at the repo root (CTE-staged 3-tier insert: app_user → kol_profile →
kol_social_channel) and additionally:

* sets ``kol_profile.avatar_url``
* inserts ``kol_portfolio_item`` rows for each portfolio image

Run ``python generate_sql.py --help`` for flags.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

ROOT = Path(__file__).resolve().parent
DEFAULT_INPUT = ROOT / "data" / "kols.json"
DEFAULT_OUTPUT = ROOT / "output" / "kol_full_import_v2.sql"

EMAIL_DOMAIN = "@kols-koc.imported"
PASSWORD_HASH_PLACEHOLDER = "$2a$10$IMPORTED.placeholder.hash.replace.before.use................"

VALID_PLATFORMS = {"TIKTOK", "FACEBOOK", "INSTAGRAM", "YOUTUBE"}

# kol_profile.avatar_url, kol_social_channel.url, kol_portfolio_item.media_url
# are all VARCHAR(500). Truncate / clean URLs to fit.
URL_MAX = 500


def clean_social_url(url: str) -> str:
    """Strip the query string and fragment from a social URL.

    Platforms add session/tracking tokens (TikTok's ``?_d=…`` can be 600+
    chars) that we don't want to persist. The canonical handle URL is
    everything before the ``?``.
    """
    if not url:
        return url
    cleaned = url.split("#", 1)[0].split("?", 1)[0]
    # Drop trailing slash for consistency, but keep one for the bare domain.
    if len(cleaned) > 1 and cleaned.endswith("/"):
        cleaned = cleaned.rstrip("/")
    return cleaned[:URL_MAX]


def sql_str(s: str | None) -> str:
    """Quote a string for SQL, escaping single quotes."""
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def sql_int(n: int | None) -> str:
    return str(n) if n is not None else "NULL"


def slug_to_email(slug: str) -> str:
    # mirror the existing convention: 'ngo-thi-kim-yen' -> 'ngo.thi.kim.yen@kols-koc.imported'
    local = re.sub(r"[^a-z0-9.]", ".", slug.lower())
    local = re.sub(r"\.+", ".", local).strip(".")
    return f"{local}{EMAIL_DOMAIN}"


def build_bio(kol: dict) -> str:
    """Match the original SQL's bio shape: 'Phân loại: ...\\n\\nLĩnh vực: ...'."""
    parts: list[str] = []
    pers = kol.get("personal_categories") or []
    serv = kol.get("service_categories") or []
    if pers:
        parts.append("Phân loại: " + ", ".join(pers))
    if serv:
        parts.append("Lĩnh vực: " + ", ".join(serv))
    bio_text = (kol.get("bio") or "").strip()
    if bio_text:
        parts.append(bio_text)
    return "\n\n".join(parts)


def image_local_to_url(local_path: str | None, prefix: str) -> str | None:
    """Convert ``data/images/<slug>/avatar.jpg`` -> ``<prefix><slug>/avatar.jpg``."""
    if not local_path:
        return None
    p = local_path.replace("\\", "/")
    needle = "data/images/"
    i = p.find(needle)
    if i < 0:
        return prefix.rstrip("/") + "/" + p
    rel = p[i + len(needle) :]
    return prefix.rstrip("/") + "/" + rel


def _truncate_url(url: str | None) -> str | None:
    if url is None:
        return None
    return url[:URL_MAX]


def avatar_url_for(kol: dict, image_url_prefix: str, use_remote: bool) -> str | None:
    if use_remote:
        return _truncate_url(kol.get("avatar_remote_url"))
    return _truncate_url(image_local_to_url(kol.get("avatar_local_path"), image_url_prefix))


def portfolio_url_for(item: dict, image_url_prefix: str, use_remote: bool) -> str | None:
    if use_remote:
        return _truncate_url(item.get("remote_url"))
    url = image_local_to_url(item.get("local_path"), image_url_prefix) or item.get("remote_url")
    return _truncate_url(url)


def normalize_kols(data: dict) -> list[dict]:
    kols = data.get("kols", [])
    # Stable order for diffability: list-page order is the existing JSON order.
    # Filter out anything missing a slug (shouldn't happen, but be defensive).
    return [k for k in kols if k.get("slug") and k.get("display_name")]


HEADER_TEMPLATE = """\
-- ======================================================================
-- KOL bulk import (regenerated by crawler/generate_sql.py)
--   Source : https://kols-koc.com/all-influencers/  (pages 1..21)
--   KOL    : {kol_count}
--   Socials: {social_count}
--   Portfolio items: {portfolio_count}
--
-- The CLEANUP block below is COMMENTED OUT by default. Uncomment it if you
-- want a clean re-import (it deletes only rows imported by this script,
-- matched by email pattern '%@kols-koc.imported').
-- ======================================================================

-- ---------------- CLEANUP (optional) ----------------
-- BEGIN;
--
-- DELETE FROM kol_portfolio_item
-- WHERE kol_profile_id IN (
--     SELECT kp.id FROM kol_profile kp
--     JOIN app_user au ON au.id = kp.user_id
--     WHERE au.email LIKE '%@kols-koc.imported'
-- );
--
-- DELETE FROM kol_social_channel
-- WHERE kol_profile_id IN (
--     SELECT kp.id FROM kol_profile kp
--     JOIN app_user au ON au.id = kp.user_id
--     WHERE au.email LIKE '%@kols-koc.imported'
-- );
--
-- DELETE FROM kol_profile
-- WHERE user_id IN (SELECT id FROM app_user WHERE email LIKE '%@kols-koc.imported');
--
-- DELETE FROM app_user WHERE email LIKE '%@kols-koc.imported';
--
-- COMMIT;
"""


IMPORT_PREAMBLE = """\

-- ---------------- IMPORT ----------------
-- NOTE: this block has NO BEGIN/COMMIT — apply.py runs cleanup + import in
-- one transaction. If you run it via psql, wrap with -1 (single transaction).

-- Stage 1: stage user input. ``rn`` is a stable row number used to map
-- app_user.id -> kol_profile, then kol_profile.id -> social channels and
-- portfolio items.
WITH user_input (rn, email, display_name, slug, bio, avatar_url) AS (
    VALUES
"""


def build_user_input(kols: list[dict], image_url_prefix: str, use_remote: bool) -> str:
    rows: list[str] = []
    for rn, kol in enumerate(kols, start=1):
        slug = kol["slug"]
        email = slug_to_email(slug)
        display_name = kol["display_name"]
        bio = build_bio(kol)
        avatar_url = avatar_url_for(kol, image_url_prefix, use_remote)
        # Cast the first row's NULLs explicitly so VALUES infers types correctly.
        if rn == 1:
            row = (
                f"        ({rn}, {sql_str(email)}, {sql_str(display_name)}, "
                f"{sql_str(slug)}, {sql_str(bio)}::TEXT, {sql_str(avatar_url)}::VARCHAR)"
            )
        else:
            row = (
                f"        ({rn}, {sql_str(email)}, {sql_str(display_name)}, "
                f"{sql_str(slug)}, {sql_str(bio)}, {sql_str(avatar_url)})"
            )
        rows.append(row)
    return ",\n".join(rows) + "\n)"


def build_socials_block(kols: list[dict]) -> str:
    rows: list[str] = []
    for kol in kols:
        slug = kol["slug"]
        seen: set[tuple[str, str]] = set()
        for ch in kol.get("socials") or []:
            platform = (ch.get("platform") or "").upper()
            if platform not in VALID_PLATFORMS:
                continue
            raw_url = ch.get("url") or ""
            if not raw_url:
                continue
            url = clean_social_url(raw_url)
            key = (platform, url)
            if key in seen:
                continue
            seen.add(key)
            username = ch.get("username")
            if username:
                username = username[:150]  # kol_social_channel.username VARCHAR(150)
            followers = int(ch.get("follower_count") or 0)
            rows.append(
                f"        ({sql_str(slug)}, {sql_str(platform)}, {sql_str(url)}, "
                f"{sql_str(username)}, {followers})"
            )
    if not rows:
        # Emit an empty no-op CTE-compatible row so the SQL stays valid.
        return "        (NULL::VARCHAR, NULL::VARCHAR, NULL::VARCHAR, NULL::VARCHAR, 0)"
    return ",\n".join(rows)


def build_portfolio_block(kols: list[dict], image_url_prefix: str, use_remote: bool) -> str:
    rows: list[str] = []
    for kol in kols:
        slug = kol["slug"]
        for item in kol.get("portfolio") or []:
            url = portfolio_url_for(item, image_url_prefix, use_remote)
            if not url:
                continue
            title = (item.get("title") or "").strip() or kol.get("display_name") or slug
            # kol_portfolio_item.title is VARCHAR(200) — truncate just in case.
            title = title[:200]
            rows.append(
                f"        ({sql_str(slug)}, {sql_str(title)}, {sql_str(url)}, 'IMAGE')"
            )
    if not rows:
        return "        (NULL::VARCHAR, NULL::VARCHAR, NULL::VARCHAR, NULL::VARCHAR)"
    return ",\n".join(rows)


def build_full_sql(kols: list[dict], image_url_prefix: str, use_remote: bool, status: str) -> str:
    social_count = sum(len(k.get("socials") or []) for k in kols)
    portfolio_count = sum(len(k.get("portfolio") or []) for k in kols)

    parts: list[str] = []
    parts.append(
        HEADER_TEMPLATE.format(
            kol_count=len(kols),
            social_count=social_count,
            portfolio_count=portfolio_count,
        )
    )
    parts.append(IMPORT_PREAMBLE)
    parts.append(build_user_input(kols, image_url_prefix, use_remote))
    # PENDING_VERIFICATION isn't allowed when we want APPROVED profiles to be
    # immediately searchable: the app may filter inactive users out, so we
    # set the user to ACTIVE/email_verified=TRUE when status=APPROVED.
    user_status = "ACTIVE" if status == "APPROVED" else "PENDING_VERIFICATION"
    user_email_verified = "TRUE" if status == "APPROVED" else "FALSE"
    parts.append(
        """,
-- Stage 2: insert app_user. ON CONFLICT keeps the import idempotent — a
-- second run sees the email already present and does nothing for that row.
inserted_users AS (
    INSERT INTO app_user (email, password_hash, role, status, email_verified)
    SELECT
        ui.email,
        '""" + PASSWORD_HASH_PLACEHOLDER + """',
        'KOL',
        '""" + user_status + """',
        """ + user_email_verified + """
    FROM user_input ui
    ORDER BY ui.rn
    ON CONFLICT (email) DO NOTHING
    RETURNING id, email
),
-- Resolve every input email to its app_user.id. CTEs share one snapshot, so
-- SELECT cannot see rows just inserted by inserted_users; we UNION the
-- RETURNING set with pre-existing rows.
all_users AS (
    SELECT id, email FROM inserted_users
    UNION ALL
    SELECT au.id, au.email
    FROM app_user au
    JOIN user_input ui ON ui.email = au.email
),
-- Stage 3: insert kol_profile when the user has none and the slug is free.
-- avatar_url is set on first import; later runs leave it untouched.
inserted_profiles AS (
    INSERT INTO kol_profile (user_id, display_name, slug, bio, avatar_url, status, avg_rating, review_count)
    SELECT
        au.id,
        ui.display_name,
        ui.slug,
        ui.bio,
        ui.avatar_url,
        '""" + status + """',
        0,
        0
    FROM user_input ui
    JOIN all_users au ON au.email = ui.email
    WHERE NOT EXISTS (SELECT 1 FROM kol_profile kp WHERE kp.user_id = au.id)
    ON CONFLICT (slug) DO NOTHING
    RETURNING id AS profile_id, slug
),
all_profiles AS (
    SELECT profile_id, slug FROM inserted_profiles
    UNION ALL
    SELECT kp.id AS profile_id, kp.slug
    FROM kol_profile kp
    JOIN user_input ui ON ui.slug = kp.slug
),
-- Stage 4: stage social channels.
social_input (slug, platform, url, username, follower_count) AS (
    VALUES
"""
    )
    parts.append(build_socials_block(kols))
    _ = use_remote  # socials don't have local files; nothing to switch.
    parts.append(
        """
),
-- Insert each (profile, url) only once. Re-runs skip rows already present.
inserted_socials AS (
    INSERT INTO kol_social_channel (kol_profile_id, platform, url, username, follower_count)
    SELECT
        ap.profile_id,
        si.platform,
        si.url,
        si.username,
        si.follower_count
    FROM social_input si
    JOIN all_profiles ap ON ap.slug = si.slug
    WHERE si.slug IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM kol_social_channel ksc
          WHERE ksc.kol_profile_id = ap.profile_id
            AND ksc.url = si.url
      )
    RETURNING id
),
-- Stage 5: stage portfolio items.
portfolio_input (slug, title, media_url, media_type) AS (
    VALUES
"""
    )
    parts.append(build_portfolio_block(kols, image_url_prefix, use_remote))
    parts.append(
        """
)
INSERT INTO kol_portfolio_item (kol_profile_id, title, media_url, media_type)
SELECT
    ap.profile_id,
    pi.title,
    pi.media_url,
    pi.media_type
FROM portfolio_input pi
JOIN all_profiles ap ON ap.slug = pi.slug
WHERE pi.slug IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM kol_portfolio_item kpi
      WHERE kpi.kol_profile_id = ap.profile_id
        AND kpi.media_url = pi.media_url
  );
"""
    )

    return "".join(parts)


def main() -> int:
    p = argparse.ArgumentParser(description="Generate import SQL from kols.json.")
    p.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    p.add_argument(
        "--image-url-prefix",
        default="/files/kol-import/",
        help=(
            "URL prefix where the downloaded images will be served from. "
            "The crawler stores them under crawler/data/images/<slug>/ — copy or "
            "mount that tree at this URL."
        ),
    )
    p.add_argument(
        "--use-remote-urls",
        action="store_true",
        help=(
            "Use the original kols-koc.com image URLs in the SQL instead of the "
            "local /files/... prefix. Useful when status=APPROVED so the avatars "
            "render immediately without any extra static-serving setup."
        ),
    )
    p.add_argument(
        "--status",
        choices=["DRAFT", "APPROVED", "PENDING", "REJECTED"],
        default="DRAFT",
        help=(
            "kol_profile.status to set for inserted rows. APPROVED also sets the "
            "associated app_user.status=ACTIVE and email_verified=TRUE so the KOL "
            "is searchable immediately."
        ),
    )
    args = p.parse_args()

    if not args.input.exists():
        print(f"Input not found: {args.input}\nRun crawl.py first.", file=sys.stderr)
        return 1

    data = json.loads(args.input.read_text(encoding="utf-8"))
    kols = normalize_kols(data)
    if not kols:
        print("No KOL records in input.", file=sys.stderr)
        return 1

    sql = build_full_sql(kols, args.image_url_prefix, args.use_remote_urls, args.status)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")

    social_count = sum(len(k.get("socials") or []) for k in kols)
    portfolio_count = sum(len(k.get("portfolio") or []) for k in kols)
    print(
        f"Wrote {args.output} — {len(kols)} KOL, {social_count} socials, "
        f"{portfolio_count} portfolio items.\n"
        f"Status: {args.status}  |  Image URLs: "
        f"{'remote (kols-koc.com)' if args.use_remote_urls else args.image_url_prefix}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
