spring.datasource.url=jdbc:postgresql://localhost:5432/kol_booking
spring.datasource.username=kol_user
spring.datasource.password=kol_secret

logging.level.kolbooking.datn=DEBUG
logging.level.org.springframework.security=DEBUG
