package kolbooking.datn.notification.domain;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_IN_PROGRESS,
    DELIVERABLE_SUBMITTED,
    DELIVERY_REVISION_REQUESTED,
    BOOKING_COMPLETED,
    BOOKING_DISPUTED,
    PAYMENT_SUCCESS,
    REVIEW_RECEIVED,
    WITHDRAW_APPROVED,
    WITHDRAW_REJECTED,
    PROFILE_APPROVED,
    PROFILE_REJECTED,
    NEW_MESSAGE,
    PRODUCT_APPLICATION_RECEIVED,
    APPLICATION_SHORTLISTED,
    APPLICATION_COUNTER_OFFERED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED
}
